import { Body, Module, Req } from '@nestjs/common'
import { Api_Controller } from '@src/plugins/Api_Controller'
import { Api_Post } from '@src/plugins/Api_Post'
import { Api_public } from '@src/App_Auth'

// ==================== util ====================
import { db1 as db } from '@src/v1/db_prisma_1'
import _ from 'lodash'
import { argsArgArrayOrObject } from 'rxjs/internal/util/argsArgArrayOrObject'

// ==================== dto ====================

@Api_Controller('材料')
export class arg_print_material {
  @Api_Post('查询-材料-列表')
  async find_list_arg_print_material(@Body() body: any, @Req() req: any) {
    console.log('find_list_arg_print_material---body', body)
    let list_arg_print_material = await db.arg_print_material.findMany()

    // 按 kind1 分组
    let group_arg_print_material = _.groupBy(list_arg_print_material, 'kind1')

    // 对"材料"组进行二次分组，按 kind2
    if (group_arg_print_material['材料']) {
      group_arg_print_material['材料'] = _.groupBy(group_arg_print_material['材料'], 'kind2')
    }

    let material_list = []
    for (let o in group_arg_print_material['材料']) {
      console.log(`111---o:`, o)
      material_list.push({ name: o, checked: false })
    }
    material_list[0].checked = true

    return { code: 200, msg: '成功', result: { list_arg_print_material, group_arg_print_material, material_list } }
  }
}

@Module({
  controllers: [arg_print_material],
  providers: [],
})
export class arg_print_material_Module {}

const list_arg_print_material = [
  {
    id: 'material_01',
    kind1: '材料',
    kind2: '光敏树脂',
    code: '9100',
    name: '9100',
    price: 278,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'material_02',
    kind1: '材料',
    kind2: '光敏树脂',
    code: '9200',
    name: '9200',
    price: 214,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'material_03',
    kind1: '材料',
    kind2: '高分子粉末',
    code: '1001',
    name: '1001',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'material_04',
    kind1: '材料',
    kind2: '高分子粉末',
    code: '1001',
    name: '1001',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'material_05',
    kind1: '材料',
    kind2: '金属粉末',
    code: '2001',
    name: '2001',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'material_06',
    kind1: '材料',
    kind2: '金属粉末',
    code: '2002',
    name: '2002',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'material_07',
    kind1: '材料',
    kind2: '线材',
    code: '3001',
    name: '3001',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'material_08',
    kind1: '材料',
    kind2: '线材',
    code: '3002',
    name: '3002',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'material_09',
    kind1: '材料',
    kind2: '陶瓷',
    code: '4001',
    name: '4001',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'material_10',
    kind1: '材料',
    kind2: '陶瓷',
    code: '4002',
    name: '4002',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'material_11',
    kind1: '材料',
    kind2: '尼龙',
    code: '5001',
    name: '5001',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'material_12',
    kind1: '材料',
    kind2: '尼龙',
    code: '5002',
    name: '5002',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'polish_01',
    kind1: '打磨',
    kind2: '',
    code: '300',
    name: '粗磨',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'polish_02',
    kind1: '打磨',
    kind2: '',
    code: '400',
    name: '粗磨#400',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'polish_03',
    kind1: '打磨',
    kind2: '',
    code: '800',
    name: '粗磨#800',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'polish_04',
    kind1: '打磨',
    kind2: '',
    code: '1200',
    name: '精磨#800',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'paint_u01',
    kind1: '喷漆',
    kind2: '哑光',
    code: '871U',
    name: '871U',
    price: 0,
    color: '871U',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'paint_u02',
    kind1: '喷漆',
    kind2: '哑光',
    code: '872U',
    name: '872U',
    price: 0,
    color: '872U',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'paint_u03',
    kind1: '喷漆',
    kind2: '哑光',
    code: '873U',
    name: '873U',
    price: 0,
    color: '873U',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'paint_c01',
    kind1: '喷漆',
    kind2: '亮光',
    code: '871C',
    name: '871C',
    price: 0,
    color: '871C',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'paint_c02',
    kind1: '喷漆',
    kind2: '亮光',
    code: '872C',
    name: '872C',
    price: 0,
    color: '872C',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'paint_c03',
    kind1: '喷漆',
    kind2: '亮光',
    code: '873C',
    name: '873C',
    price: 0,
    color: '873C',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'nut_n01',
    kind1: '螺母',
    kind2: '',
    code: 'M2*2',
    name: 'M2*2',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'nut_n02',
    kind1: '螺母',
    kind2: '',
    code: 'M2*3',
    name: 'M2*3',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'nut_n03',
    kind1: '螺母',
    kind2: '',
    code: 'M2*5',
    name: 'M2*5',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'nut_n04',
    kind1: '螺母',
    kind2: '',
    code: 'M3*3',
    name: 'M3*3',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'nut_n05',
    kind1: '螺母',
    kind2: '',
    code: 'M3*5',
    name: 'M3*5',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'nut_n06',
    kind1: '螺母',
    kind2: '',
    code: 'M4*4',
    name: 'M4*4',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'nut_n07',
    kind1: '螺母',
    kind2: '',
    code: 'M4*8',
    name: 'M4*8',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'height_01',
    kind1: '层高',
    kind2: '',
    code: '0.1mm',
    name: '0.1mm',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
  {
    id: 'height_02',
    kind1: '层高',
    kind2: '',
    code: '0.05mm',
    name: '0.05mm',
    price: 0,
    color: '',
    remark: '',
    url_img: '',
    diameter_inner: 0,
    diameter_out: 0,
    length: 0,
    with: 0,
    height: 0,
  },
]
