import type { RouteRecordRaw } from 'vue-router'

export const view_admin: RouteRecordRaw[] = [
  {
    path: '/view/admin/users',
    name: '用户管理',
    component: () => import('../view/admin/user.vue'),
  },
  {
    path: '/view/admin/orders',
    name: '订单管理',
    component: () => import('../view/admin/order.vue'),
  },
  {
    path: '/view/admin/file_sys',
    name: '文件系统',
    component: () => import('../view/admin/file_sys/file_sys.vue'),
  },
]

let list_data_menu = [
  {
    id: 'menu_1',
    name: '首页',
    path: '/home',
    remark: null,
    type: 'menu',
    is_permiss: false,
    is_view: false,
    is_find: false,
    is_save: false,
    is_del: false,
    parent_id: null,
    children: [],
  },
  {
    id: 'menu_2',
    name: '系统设置',
    path: '/system',
    remark: null,
    type: 'dir',
    is_permiss: false,
    is_view: false,
    is_find: false,
    is_save: false,
    is_del: false,
    parent_id: null,
    children: [
      {
        id: 'sub_2001',
        name: '组织人员',
        path: '/system/user',
        remark: null,
        type: 'menu',
        is_permiss: false,
        is_view: false,
        is_find: false,
        is_save: false,
        is_del: false,
        parent_id: 'menu_2',
        children: [],
      },
      {
        id: 'sub_2002',
        name: '组织管理',
        path: '/system/depart',
        remark: null,
        type: 'menu',
        is_permiss: false,
        is_view: false,
        is_find: false,
        is_save: false,
        is_del: false,
        parent_id: 'menu_2',
        children: [],
      },
    ],
  },
  {
    id: 'menu_3',
    name: '商城管理',
    path: '/mall',
    remark: null,
    type: 'dir',
    is_permiss: false,
    is_view: false,
    is_find: false,
    is_save: false,
    is_del: false,
    parent_id: null,
    children: [
      {
        id: 'sub_3001',
        name: '订单管理',
        path: '/mall/order',
        remark: null,
        type: 'menu',
        is_permiss: false,
        is_view: false,
        is_find: false,
        is_save: false,
        is_del: false,
        parent_id: 'menu_3',
        children: [],
      },
      {
        id: 'sub_3002',
        name: '商品管理',
        path: '/mall/product',
        remark: null,
        type: 'menu',
        is_permiss: false,
        is_view: false,
        is_find: false,
        is_save: false,
        is_del: false,
        parent_id: 'menu_3',
        children: [],
      },
      {
        id: 'sub_3003',
        name: '财务管理',
        path: '/mall/finance',
        remark: null,
        type: 'menu',
        is_permiss: false,
        is_view: false,
        is_find: false,
        is_save: false,
        is_del: false,
        parent_id: 'menu_3',
        children: [],
      },
    ],
  },
]



//根据list_data_menu用函数生成路由   类似这样     { path: '/view/admin/users', name: '用户管理',    component: () => import('../view/admin/user.vue'),  },



