import type { RouteRecordRaw } from 'vue-router'

export const view_admin: RouteRecordRaw[] = [
  {
    name: '首页',
    path: '/view/admin/home',
    component: () => import('../view/admin/home/home.vue'),
  },
  // 系统设置
  {
    name: '系统设置',
    path: '/view/admin/system',
    children: [
      {
        name: '用户管理',
        path: '/view/admin/system/user',
        component: () => import('../view/admin/system/user/user.vue'),
      },
      {
        name: '部门管理',
        path: '/view/admin/system/depart',
        component: () => import('../view/admin/system/depart/depart.vue'),
      },
    ],
  },
  // 商城管理
  {
    name: '商城管理',
    path: '/view/admin/shop',
    children: [
      {
        name: '商品管理',
        path: '/view/admin/shop/product',
        component: () => import('../view/admin/shop/product/product.vue'),
      },
      {
        name: '订单管理',
        path: '/view/admin/shop/order',
        component: () => import('../view/admin/shop/order/order.vue'),
      },
      {
        name: '财务管理',
        path: '/view/admin/shop/finance',
        component: () => import('../view/admin/shop/finance/finance.vue'),
      },
    ],
  },
]

let list_data_menu = [
  {
    id: 'menu_1',

    path: '/home',
    remark: null,
    type: 'menu',
    is_permiss: false,
    is_view: false,
    is_find: false,
    is_save: false,
    is_del: false,
    parent_id: null,
    children: [],
  },
  {
    id: 'menu_2',
    name: '系统设置',
    path: '/system',
    remark: null,
    type: 'dir',
    is_permiss: false,
    is_view: false,
    is_find: false,
    is_save: false,
    is_del: false,
    parent_id: null,
    children: [
      {
        id: 'sub_2001',
        name: '用户管理',
        path: '/system/user',
        remark: null,
        type: 'menu',
        is_permiss: false,
        is_view: false,
        is_find: false,
        is_save: false,
        is_del: false,
        parent_id: 'menu_2',
        children: [],
      },
      {
        id: 'sub_2002',
        name: '组织管理',
        path: '/system/depart',
        remark: null,
        type: 'menu',
        is_permiss: false,
        is_view: false,
        is_find: false,
        is_save: false,
        is_del: false,
        parent_id: 'menu_2',
        children: [],
      },
    ],
  },
  {
    id: 'menu_3',
    name: '商城管理',
    path: '/mall',
    remark: null,
    type: 'dir',
    is_permiss: false,
    is_view: false,
    is_find: false,
    is_save: false,
    is_del: false,
    parent_id: null,
    children: [
      {
        id: 'sub_3001',
        name: '订单管理',
        path: '/mall/order',
        remark: null,
        type: 'menu',
        is_permiss: false,
        is_view: false,
        is_find: false,
        is_save: false,
        is_del: false,
        parent_id: 'menu_3',
        children: [],
      },
      {
        id: 'sub_3002',
        name: '商品管理',
        path: '/mall/product',
        remark: null,
        type: 'menu',
        is_permiss: false,
        is_view: false,
        is_find: false,
        is_save: false,
        is_del: false,
        parent_id: 'menu_3',
        children: [],
      },
      {
        id: 'sub_3003',
        name: '财务管理',
        path: '/mall/finance',
        remark: null,
        type: 'menu',
        is_permiss: false,
        is_view: false,
        is_find: false,
        is_save: false,
        is_del: false,
        parent_id: 'menu_3',
        children: [],
      },
    ],
  },
]
